from django.db import models
from pgvector.django import VectorField

from django.conf import settings


class Document(models.Model):
    """
    Represents an uploaded document.

    Stores metadata only — the actual text content lives in the
    related Chunk records. Deleting a Document cascades to delete
    all of its chunks and their embeddings.
    """

    filename = models.CharField(
        max_length=255,
        help_text="Original filename of the uploaded document.",
    )
    file_type = models.CharField(
        max_length=10,
        help_text="File extension without the dot (e.g., 'pdf', 'docx').",
    )
    uploaded_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when the document was uploaded.",
    )

    class Meta:
        ordering = ['-uploaded_at']
        db_table = 'documents'

    def __str__(self) -> str:
        return f"{self.filename} ({self.file_type})"


class Chunk(models.Model):
    """
    A text chunk extracted from a Document, with its embedding vector.

    Each document is split into overlapping chunks of ~500 characters.
    Each chunk's embedding is a 384-dimensional vector generated by
    the sentence-transformers model (all-MiniLM-L6-v2).

    The embedding field uses pgvector's VectorField, which enables
    cosine similarity search directly in PostgreSQL using the <=> operator.
    """

    document = models.ForeignKey(
        Document,
        on_delete=models.CASCADE,
        related_name='chunks',
        help_text="The document this chunk belongs to.",
    )
    chunk_index = models.IntegerField(
        help_text="Position of this chunk within the document (0-indexed).",
    )
    content = models.TextField(
        help_text="The actual text content of this chunk.",
    )
    embedding = VectorField(
        dimensions=settings.EMBEDDING_DIMENSION,
        help_text="384-dimensional embedding vector from all-MiniLM-L6-v2.",
    )
    created_at = models.DateTimeField(
        auto_now_add=True,
        help_text="Timestamp when this chunk was created.",
    )

    class Meta:
        ordering = ['document', 'chunk_index']
        db_table = 'chunks'
        indexes = [
            models.Index(fields=['document', 'chunk_index']),
        ]

    def __str__(self) -> str:
        return f"Chunk {self.chunk_index} of {self.document.filename}"
