"""
LLM Service — Communicates with the local Ollama instance.

This service acts as an HTTP client for Ollama's REST API.
It sends the constructed RAG prompt to the local Gemma model
and returns the generated answer.

No LangChain or complex SDKs used. Just the standard requests library.
"""

import logging

import requests
from django.conf import settings

logger = logging.getLogger(__name__)


class LLMService:
    """
    Handles communication with the local Ollama LLM.
    """

    def __init__(self):
        # We read these from settings, which pulls from .env
        # e.g., OLLAMA_URL = 'http://localhost:11434'
        #       MODEL_NAME = 'gemma3:4b'
        self.base_url = settings.OLLAMA_URL.rstrip('/')
        self.model_name = settings.MODEL_NAME
        
        # The specific endpoint for generating a response
        self.generate_url = f"{self.base_url}/api/generate"

    def generate(self, prompt: str) -> str:
        """
        Send a prompt to Ollama and return the generated text.

        This uses the /api/generate endpoint. We set 'stream': False
        so that Ollama waits until the entire response is generated
        before returning the HTTP response. (Per project rules, no streaming).

        Args:
            prompt: The full prompt string (system instructions + context + question).

        Returns:
            The text answer generated by the LLM.

        Raises:
            ConnectionError: If Ollama is not running or unreachable.
            ValueError: If Ollama returns an error (e.g., model not found).
        """
        payload = {
            "model": self.model_name,
            "prompt": prompt,
            "stream": False,  # We want the full response at once
        }

        logger.info("Sending prompt to Ollama (model: %s)", self.model_name)
        logger.debug("Prompt length: %d characters", len(prompt))

        try:
            # Add a reasonable timeout in case model generation takes a while
            response = requests.post(
                self.generate_url, 
                json=payload, 
                timeout=120
            )
            
            # Raise an HTTPError if the status code is 4xx or 5xx
            response.raise_for_status()
            
            # The response is JSON: {"model": "...", "response": "The actual answer...", ...}
            data = response.json()
            answer = data.get("response", "")
            
            logger.info("Received answer from Ollama (length: %d)", len(answer))
            return answer.strip()

        except requests.exceptions.ConnectionError as e:
            logger.error("Failed to connect to Ollama at %s", self.base_url)
            raise ConnectionError(
                f"Could not connect to Ollama at {self.base_url}. "
                "Is the Ollama service running?"
            ) from e
            
        except requests.exceptions.HTTPError as e:
            # This happens if the model isn't downloaded, e.g., 404
            logger.error("Ollama API returned an error: %s", e.response.text)
            raise ValueError(
                f"Ollama error (HTTP {e.response.status_code}): {e.response.text}"
            ) from e
            
        except requests.exceptions.Timeout as e:
            logger.error("Ollama request timed out after 120 seconds")
            raise ConnectionError(
                "Ollama took too long to respond. The model might be "
                "too large for your hardware, or still loading."
            ) from e
